# Tell Mongoid which environment this configuration is for.
development:
  # This starts the session configuration settings. You may have as
  # many sessions as you like, but you must have at least 1 named
  # 'default'.
  sessions:
      # Define the default session.
      default:
          # A session can have any number of hosts. Usually 1 for a single
          # server setup, and at least 3 for a replica set. Hosts must be
          # an array of host:port pairs. This session is single server.
          hosts:
            - localhost: 27017
          # Define the default database name.  
          database: mongoid
      options:
        allow_dynamic_fields: true
        safe: true  
        
defaults: &defaults
    host: localhost
    # slaves: 
      # - host: slave1.local
      #   port: 27018
      # - host: slave2.local
      #   port: 27019
      
development:
  <<: *defaults
  database: mongoid_development
  
test: 
  <<: *defaults
  database: mongoid_test
  
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
    options:
      skip_version_check: true
      safe: true